### ISSUE TITLE
Vercel Deployment settings

### ISSUE THREAD

**Issue by mnik01** [mnik01/viteRPC#1]
<img width="856" alt="image" src="https://github.com/mnik01/viteRPC/assets/39025497/fa990cde-fc51-43da-9bbb-cfb9dcaf814d">

<img width="867" alt="image" src="https://github.com/mnik01/viteRPC/assets/39025497/a3d13fb0-277b-4e58-b202-18d235deb6ad">

---
Commands:
`pnpm --filter=react build`

`dist`

`pnpm i`

`pnpm dev`

Feel free to replace pnpm with npm (also delete pnpm lock and generate npm lock file)

**Comment by samkim28** [comment]
thank you for this! this only deploys the client side right? did you deploy the trpc in a separate project? i ended up having to deploy the trpc server in a separate project, but i've been having CORS origin errors that I can't seem to find a solution for. I've tried updating the `vercel.json` file that was suggested in Vercel docs but still not working.

**Comment by mnik01** [comment]
You right to vercel deployed only client side.
Server side deployed to railway.

Here is my railway settings:
<img width="567" alt="image" src="https://github.com/mnik01/viteRPC/assets/39025497/af01e655-676d-4691-9c78-7fe53a12ef93">

<img width="600" alt="image" src="https://github.com/mnik01/viteRPC/assets/39025497/944cd188-fb4d-4792-88b9-da57ae8baefb">

<img width="579" alt="image" src="https://github.com/mnik01/viteRPC/assets/39025497/7d77e776-9c19-454e-8329-4bf96f2d6477">

And env:
<img width="676" alt="image" src="https://github.com/mnik01/viteRPC/assets/39025497/8d4e0200-63eb-4315-b2bc-78e39fdc811c">

@samkim28
